name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: sudo apt-get update && sudo apt-get install -y meson cmake libx11-dev
    - name: configure
      run: meson setup -Dprefix=/ build
    - name: compile
      run: meson compile -j4 -C build
    - install:
      run: meson install -C build --destdir="stage"
